import { Dimensions } from 'react-native';
import ENV from './Environment';

const APP_CONSTANTS = {
  URLS: {
    sendNotification: `${ENV.API_HOST}/notification/send`,
  },
  APP_MESSAGES: {
    NOINTERNET: 'You are disconnected! Please connect to Internet',
    EDITPROFILE: 'To edit, please go to the My Profile screen',
    NODATA: 'No data found',
    EMP_WELCOME: 'Welcome to your dashboard. No recent bookings found!',
    WEB_SERVICE_ERR_MESSAGE: 'No network connection could be found',
    NODOCUMENTSMESSAGE: 'No Documents Found',
  },
  IMAGES: {
    parisoLogo: require('../../assets/icons/pariso_trans_logo.png'),
    parisoCover: require('../../assets/images/cover_parsio.jpg'),
    iconDrawerHome: require('../../assets/images/drawer/home.png'),
    iconTabHome: require('../../assets/images/tabbar/home.png'),
    iconWallet: require('../../assets/images/drawer/wallet-outline.png'),
    iconEmptyCart: require('../../assets/icons/empty-cart.png'),
    iconSettings: require('../../assets/images/drawer/settings.png'),
    iconLogin: require('../../assets/icons/login.png'),
    iconLogout: require('../../assets/icons/iconLogout.png'),
    iconSignup: require('../../assets/icons/signup.png'),
    iconUser: require('../../assets/images/drawer/user.png'),
    avatar: require('../../assets/images/RNS_nerd.png'),
    iconMenu: require('../../assets/images/drawer/menu.png'),
    background: require('../../assets/images/background.png'),
    headerBackground: require('../../assets/images/topBarBg.png'),
    arrowBack: require('../../assets/images/icons/arrow-back.png'),
    loginIcon: require('../../assets/icons/loginIcon.jpeg'),
    cameraIcon: require('../../assets/icons/camera.png'),
    regIcon: require('../../assets/icons/loginIcon.jpeg'),
    iconDrawerBooking: require('../../assets/images/drawer/bookings.png'),
    iconTabBooking: require('../../assets/images/tabbar/bookings.png'),
    iconSearch: require('../../assets/icons/magnify.png'),
  },
  RegisterForm: {
    name: 'Name',
    nameError: 'Please add a valid name',
    age: 'Age',
    ageError: 'Please add a valid age',
    password: 'Password',
    passwordError: 'Please add a valid password',
    mobile: 'Mobile Phone',
    mobileError: 'Please add a valid mobile phone',
    date: 'Date of Birth',
    dateError: 'Please add a valid date of birth',
    email: 'Email',
    emailError: 'Please add a valid email address',
    send: 'Register',
  },
  SCREENS_NAMES: {
    HOME: 'Home Screen',
    PROFILE: 'Profile Screen',
    EMP_DASHBOARD: 'Employee Dashboard',
    LOGIN: 'Login',
    SIGNUP: 'Register',
    BOOKING_DETAILS: 'Booking Details',
  },
  DEVICE_DIMENSIONS: {
    SCREENHEIGHT: Dimensions.get('window').height,
    SCREENWIDTH: Dimensions.get('window').width,
  },
  BUTTON_TEXT: {
    SUBMIT: 'Submit',
    LOGIN: 'Login',
    RESEND: 'Resend',
    REGISTERBUTTON: 'Register',
    EDIT: 'EDIT',
    LOGOUT: 'Log out',
    GO: 'Go',
    CANCEL: 'Cancel',
    ADDIMAGE: 'Add Image',
    DELETEIMAGE: 'Delete Image',
    BOOKED: 'BOOKED',
    ACCEPT: 'Accept',
  },
  TIME_SLOTS: [
    {
      label: '06 AM - 10 AM',
      start: new Date().setHours(6, 0, 0, 0),
      end: new Date().setHours(10, 0, 0, 0),
    },
    {
      label: '10 AM - 02 PM',
      start: new Date().setHours(10, 0, 0, 0),
      end: new Date().setHours(14, 0, 0, 0),
    },
    {
      label: '02 PM - 06 PM',
      start: new Date().setHours(14, 0, 0, 0),
      end: new Date().setHours(18, 0, 0, 0),
    },
    {
      label: '06 PM - 08 PM',
      start: new Date().setHours(18, 0, 0, 0),
      end: new Date().setHours(20, 0, 0, 0),
    },
  ],
};

export default APP_CONSTANTS;
