export const NOTIFICATION_CONSTANTS = {
  SEND_NEW_ORDER_NOTIFICATION_REQUEST: 'SEND_NEW_ORDER_NOTIFICATION_REQUEST',
  SEND_NEW_ORDER_NOTIFICATION_SUCCESS: 'SEND_NEW_ORDER_NOTIFICATION_SUCCESS',
  SEND_NEW_ORDER_NOTIFICATION_FAILURE: 'SEND_NEW_ORDER_NOTIFICATION_FAILURE',
  WAKE_NOTIFICATION_SERVER_REQUEST: 'WAKE_NOTIFICATION_SERVER_REQUEST',
  WAKE_NOTIFICATION_SERVER_SUCCESS: 'WAKE_NOTIFICATION_SERVER_SUCCESS',
  WAKE_NOTIFICATION_SERVER_FAILURE: 'WAKE_NOTIFICATION_SERVER_FAILURE',
};
