export const GLOBALCARTANDCHECKOUTCONSTANTS = {
  FETCH_MY_CART_ITEMS_REQUEST: 'FETCH_MY_CART_ITEMS_REQUEST',
  FETCH_MY_CART_ITEMS_SUCCESS: 'FETCH_MY_CART_ITEMS_SUCCESS',
  FETCH_MY_CART_ITEMS_FAILURE: 'FETCH_MY_CART_ITEMS_FAILURE',
};
